spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=LEGACY
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

server:
  servlet:
    encoding:
      force: true